# Generated by Django 4.0.2 on 2022-02-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=12)),
                ('size', models.CharField(choices=[('Size S', 'Size S'), ('Size M', 'Size M'), ('Size L', 'Size L'), ('Size XL', 'Size XL')], default='Size M', max_length=9)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
